version: '3.8'

services:
  web:
    container_name: ${JOB_NAME}
    image: ${JOB_NAME}:1.${BUILD_NUMBER}
    restart: always
    expose:
      - 80
    networks:
      - npm

networks:
  npm:
    external: true
