version: '3.8'

services:
  web:
    container_name: osb.im
    image: osb.im:1.${BUILD_NUMBER}
    restart: always
    ports:
      - 9010:80
    networks:
      - npm

networks:
  npm:
    external:
      name: npm
